name: 'Setup Python and uv'
description: 'Sets up Python 3.10 and uv with caching'
runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - id: setup-uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.10"
        enable-cache: true
